name: User Issue

on:
  issues:
    types: [unlabeled]

jobs:
  user_isue_check_labels:
    runs-on: ubuntu-latest
    steps:
    - name: if_issue
      if: |
        github.event.issue &&
        contains(github.event.issue.labels.*.name, 'User') &&
        ${{ github.event.issue == 'Draft' }}
      run: |
        echo this is an issue of type user and its not a draft, we can proceed
    - name: Deploy Issue
      id: issuePost
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.USER_ISSUE_POST_URL }}
        contentType: "application/json"
        method: 'POST'
        escapeData: 'true'
        data: '{"id":"${{github.event.issue.id}}","title":"${{github.event.issue.title}}","body":"${{github.event.issue.body}}"}'
    - name: Show Response
      run: echo ${{ steps.issuePost.outputs.response }}
