name: User Issue

on:
  issues:
    types: [unlabeled]

jobs:
  user_isue_check_labels:
    runs-on: ubuntu-latest
    steps:
    - name: if_issue
      if: |
        github.event.issue &&
        contains(github.event.issue.labels.*.name, 'User') &&
        ${{ github.event.issue == 'Draft' }}
      run: |
        echo this is an issue of type user and its not a draft, we can proceed
    - name: Deploy Issue
      id: issuePost
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.USER_ISSUE_POST_URL }}
        contentType: "application/json"
        method: 'POST'
        escapeData: 'true'
        data: '{"id":"${{github.event.issue.id}}","title":"${{github.event.issue.title}}","body":"${{github.event.issue.body}}","user":"${{github.event.issue.user.login}}"}'
        
    - name: Reply to Issue if Error
      if: ${{ fromJSON(steps.issuePost.outputs.response).code != 'OK' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
         There was an error processing your request :(
         Error code: '${{fromJSON(steps.issuePost.outputs.response).code}}'
         Error message: '${{fromJSON(steps.issuePost.outputs.response).message}}'
    - name: Move Issue to Draft if Error
      if: ${{ fromJSON(steps.issuePost.outputs.response).code != 'OK' }}
      uses: andymckay/labeler@master
      with:
        add-labels: "Draft"
        remove-labels: "Published"
         
    - name: Reply to Issue if Success
      if: ${{ fromJSON(steps.issuePost.outputs.response).code == 'OK' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
         The user was succesfully created or updated, edit the original issue to update the user again.
    - name: Move Issue to Published if Success
      if: ${{ fromJSON(steps.issuePost.outputs.response).code == 'OK' }}
      uses: andymckay/labeler@master
      with:
        add-labels: "Published"  
